"""集中配置：业务口径、治理阈值和规则挖掘参数。"""
MIN_VALID_RATE = 0.20
TOP1_RATIO_MAX = 0.98
UNIQUE_RATIO_ID = 0.95
LOW_CARDINALITY_MAX = 20
MEDIUM_CARDINALITY_MAX = 100
MIN_CATEGORY_COUNT = 30
MIN_CATEGORY_RATE = 0.005
MIN_RULE_SAMPLE_NEW = 30
MIN_RULE_SAMPLE_OLD = 20
MIN_BAD_COUNT = 10
MIN_RULE_COVERAGE = 0.005
MIN_LIFT = 1.20
STRONG_LIFT = 1.30
STRICT_A_LIFT = 1.50
STRICT_A_HIT_COUNT = 40
STRICT_A_BAD_COUNT = 20
STRICT_A_COVERAGE = 0.02
STRICT_A_BOOTSTRAP = 0.95
JACCARD_SIMILAR = 0.80
JACCARD_SAME_GROUP = 0.90
BOOTSTRAP_N = 200
BOOTSTRAP_SAMPLE_RATE = 1.0
RANDOM_STATE = 42
MAX_RULES_PER_FIELD = 3
NUMERIC_BINS = 10
SMALL_SEGMENT_THRESHOLD = 300
EXTREME_BAD_RATE = 0.95
EXTREME_GOOD_RATE = 0.95
EXTREME_LIFT = 2.5
MANUAL_DECISIONS = ("KEEP", "EXCLUDE", "SUSPECT_LEAKAGE", "IDENTIFIER", "REVIEW")
SPECIAL_MISSING = {"", "null", "NULL", "none", "None", "nan", "NAN", "not get", "not_get", "unknown", "UNKNOWN", "other", "OTHER"}
SPECIAL_NUMERIC = {-999, -9999, -99999}
IDENTIFIER_TOKENS = ("id", "uuid", "phone", "mobile", "imei", "oaid", "android_id", "ip", "bvn", "card_no", "bank_card", "email", "address_detail")
ID_NAMES = ("id", "client_id", "user_id", "order_id", "apply_id", "application_id", "request_id", "contract_id", "loan_id", "bill_id", "trace_id", "uuid")
LEAKAGE_TOKENS = ("target", "label", "default", "dpd", "overdue", "repay", "payment", "pay_type", "status", "result", "collection", "writeoff", "write_off", "bad_flag", "loan_result", "final_result")
MODEL_TOKENS = ("score", "final_score", "model_score", "pred", "prediction", "prob", "probability", "risk_score")
IDENTIFIER_SEMANTIC_TOKENS = ("phone", "phone_number", "mobile", "telephone", "bvn", "imei", "oaid", "android_id", "device_id", "card_no", "bank_card", "account_no", "passport", "national_id", "nin")
POST_LOAN_TOKENS = ("fact_back", "fact_repay", "actual_repay", "actual_repayment", "settle_time", "collection_time", "overdue_days", "days_past_due", "dpd", "repay_status", "repayment_status", "overdue_status", "loan_result", "final_result", "approval_result", "collection_status", "writeoff", "write_off", "default_flag", "bad_flag")
LEAKAGE_SUSPECT_TOKENS = ("risk_over_days", "risk_over", "overdue", "dpd", "past_due", "default")
DERIVATION_SUGGESTIONS = "申请次数；近6h申请量；近24h申请量；近7d申请量；共享用户数；关联client数量；关联设备数；历史命中次数；关联BVN数量；IP网段；设备共享度"
