import {useEffect,useState} from 'react';
import {BrainCircuit,RefreshCw} from 'lucide-react';
import {getExperimentMemory,trainSurrogate} from '../api/client';
import {Empty,Metric,Tag} from '../components/Common';
import {BusinessLabel,MetricHelp} from '../components/BusinessLabel';
import {surrogateLabels} from '../i18n/businessLabels';
const pct=(v:any)=>`${((Number(v)||0)*100).toFixed(1)}%`;
export default function ExperimentMemoryPage({datasetId,onError}:{datasetId:string;onError:(x:string)=>void}){
 const [data,setData]=useState<any>(null),[busy,setBusy]=useState(false);
 const load=async()=>{if(!datasetId)return;setBusy(true);try{setData((await getExperimentMemory(datasetId)).data)}catch(e:any){onError(e?.response?.data?.detail||e.message)}finally{setBusy(false)}};useEffect(()=>{load()},[datasetId]);
 const train=async()=>{if(!window.confirm('确认使用真实实验记录重新训练历史实验预测模型？该预测只作辅助参考。'))return;setBusy(true);try{await trainSurrogate(datasetId,true);await load()}catch(e:any){onError(e?.response?.data?.detail||e.message);setBusy(false)}};
 if(!datasetId)return <div className="page"><Empty title="尚未选择数据集" text="运行模型实验后，系统会自动积累实验记忆。"/></div>;
 const outcomes=data?.outcomes||{},credits=data?.credits||{},model=data?.surrogate||{};
 const table=(title:string,rows:any[],specific=false)=><section className="card"><h3>{title}</h3>{rows?.length?<table><thead><tr><th>取值</th>{specific&&<th>模型</th>}<th>样本数</th><th>正向比例</th><th>平滑后比例</th><th>平均 ΔAUC</th><th>可信程度</th></tr></thead><tbody>{rows.slice(0,12).map((x:any)=><tr key={`${x.value}-${x.model_type||''}`}><td>{x.value}</td>{specific&&<td>{x.model_type}</td>}<td>{x.sample_count} / 失败 {x.failed_count}</td><td>{pct(x.positive_rate)}</td><td>{pct(x.smoothed_positive_rate)}</td><td>{Number(x.avg_delta_auc||0).toFixed(4)}</td><td><Tag>{x.confidence}</Tag></td></tr>)}</tbody></table>:<p className="muted">暂无真实实验统计。</p>}</section>;
 const metrics=model.metrics||{},gate=metrics.active_gate||{},reg=metrics.regression?.delta_oot_auc||{},rank=metrics.ranking||{},cal=metrics.calibration||{};
 return <div className="page"><div className="page-title"><div><h2>实验记忆</h2><p>历史预测只决定参考优先级；真实的增量效果实验才是事实依据。</p></div><div className="agent-actions"><button className="secondary" disabled={busy} onClick={load}><RefreshCw size={15}/>刷新</button><button disabled={busy} onClick={train}><BrainCircuit size={15}/>人工训练历史预测</button></div></div><div className="metrics"><Metric label="实验总数" value={data?.total_experiments||0}/><Metric label="正向有效" value={outcomes.POSITIVE||0} tone="tone-a"/><Metric label="暂无明显增益" value={outcomes.NEUTRAL||0}/><Metric label="负向影响" value={outcomes.NEGATIVE||0} tone="tone-review"/><Metric label="不稳定 / 失败" value={(outcomes.UNSTABLE||0)+(outcomes.FAILED||0)}/></div><section className="card"><h3>历史实验预测诊断与校准</h3><div className="plan-row"><b>状态：<BusinessLabel value={model.status||'INSUFFICIENT_DATA'} map={surrogateLabels}/></b><span title={`技术原因：${gate.why||model.reason||'Not trained'}`}>说明：{model.status==='ACTIVE'?'已通过辅助预测门槛':'尚未满足启用条件'}</span><span>训练样本：{model.training_count||0}</span><span>时间切分 <MetricHelp name="AUC"/>：{metrics.classification?.auc?.toFixed?.(3)||'—'}</span><span>排序相关性：{reg.spearman?.toFixed?.(3)||'—'}</span><span>预测排序 NDCG@10：{rank.surrogate?.ndcg_at_10?.toFixed?.(3)||'—'}</span><span>系统规则 NDCG@10：{rank.phase5?.ndcg_at_10?.toFixed?.(3)||'—'}</span><span>校准误差：{cal.before?.brier_score?.toFixed?.(3)||'—'} → {cal.after?.brier_score?.toFixed?.(3)||'—'}</span></div>{model.status!=='ACTIVE'&&<div className="warning-box">历史实验预测当前仅作旁路观察；未通过时间切分和排序门槛时，不参与最终排序，系统继续按既有规则执行。</div>}</section><div className="grid-2">{table('特征类型效果',credits.feature_types)}{table('业务语义效果',credits.semantic_domains)}{table('实验动作效果',credits.actions)}{table('不同模型下的效果',credits.model_specific,true)}</div></div>
}
