import {useEffect,useState} from 'react';
import {Braces,CheckCircle2,Play,RefreshCw,ShieldAlert,Wrench} from 'lucide-react';
import {compileFeature,featureCapabilities,featureExecutions,featureGaps,featurePlans,featureSpecs,generateFeature,generatedFeatures,rebuildFeature} from '../api/client';

type Props={datasetId:string;onError:(message:string)=>void};
const executable=(status:string)=>['SUPPORTED_TEMPLATE','COMPOSABLE_DSL'].includes(status);
const errorText=(e:any)=>String(e?.response?.data?.detail?.message||e?.response?.data?.detail||e?.message||e);

export default function FeatureEnginePage({datasetId,onError}:Props){
 const [tab,setTab]=useState<'specs'|'plans'|'generated'>('specs'),[specs,setSpecs]=useState<any[]>([]),[plans,setPlans]=useState<any[]>([]),[features,setFeatures]=useState<any[]>([]),[executions,setExecutions]=useState<any[]>([]),[gaps,setGaps]=useState<any[]>([]),[capabilities,setCapabilities]=useState<any>(null),[selected,setSelected]=useState<any>(null),[busy,setBusy]=useState('');
 const refresh=async()=>{if(!datasetId)return;try{const [s,p,f,e,g,c]=await Promise.all([featureSpecs(datasetId),featurePlans(datasetId),generatedFeatures(datasetId),featureExecutions(datasetId),featureGaps(datasetId),featureCapabilities()]);setSpecs(s.data);setPlans(p.data);setFeatures(f.data);setExecutions(e.data);setGaps(g.data);setCapabilities(c.data)}catch(e){onError(errorText(e))}};
 useEffect(()=>{refresh()},[datasetId]);
 const act=async(key:string,fn:()=>Promise<any>)=>{setBusy(key);try{const result=await fn();setSelected(result.data);await refresh()}catch(e){onError(errorText(e))}finally{setBusy('')}};
 if(!datasetId)return <div className="empty"><Wrench size={34}/><b>请先导入数据</b><p>Feature Engine 需要已加载的数据集、FeatureSpec 和人工执行确认。</p></div>;
 return <div className="feature-engine-page"><div className="page-title"><div><h2>Feature Engine</h2><p>受控 DSL / AST · 确定性 Python Executor · 人工 Generate · 可重建 Lineage</p></div><button className="secondary" onClick={refresh}><RefreshCw size={14}/>刷新</button></div>
  <div className="metrics compact"><div className="metric-card"><span>FeatureSpec</span><b>{specs.length}</b><small>Proposal normalization</small></div><div className="metric-card"><span>Compiled</span><b>{plans.length}</b><small>Execution plans</small></div><div className="metric-card tone-a"><span>Generated</span><b>{features.filter(x=>x.status==='GENERATED').length}</b><small>Not approved</small></div><div className="metric-card tone-review"><span>Capability Gaps</span><b>{gaps.length}</b><small>Explicit requirements</small></div><div className="metric-card"><span>Executions</span><b>{executions.length}</b><small>Audited runs</small></div></div>
  <div className="feature-tabs"><button className={tab==='specs'?'active secondary':'secondary'} onClick={()=>setTab('specs')}>Proposal / Spec</button><button className={tab==='plans'?'active secondary':'secondary'} onClick={()=>setTab('plans')}>Compiled</button><button className={tab==='generated'?'active secondary':'secondary'} onClick={()=>setTab('generated')}>Generated</button></div>
  {tab==='specs'&&<section className="card"><h3>FeatureSpec Registry</h3>{specs.length?<div className="table-wrap"><table><thead><tr><th>Name</th><th>Type</th><th>Sources</th><th>DSL</th><th>Version</th><th>Action</th></tr></thead><tbody>{specs.map(x=><tr key={x.feature_spec_id}><td><b>{x.feature_name}</b><small>{x.business_intent}</small></td><td>{x.feature_type}</td><td>{x.source_fields?.join(', ')}</td><td><code>{x.dsl_expression||'—'}</code></td><td>{x.version}</td><td><button disabled={!!busy} onClick={()=>act(x.feature_spec_id,()=>compileFeature(datasetId,x.feature_spec_id))}><Braces size={13}/>{busy===x.feature_spec_id?'Compiling':'Compile'}</button></td></tr>)}</tbody></table></div>:<p className="muted">尚无 FeatureSpec。请先在 Analysis Agent 的 Feature Proposal 上点击 Compile。</p>}</section>}
  {tab==='plans'&&<section className="card"><h3>Execution Plans</h3>{plans.length?<div className="engine-grid">{plans.map(x=><article className="engine-card" key={x.plan_id} onClick={()=>setSelected(x)}><span className={`tag ${executable(x.compiler_status)?'tag-a':'tag-review'}`}>{x.compiler_status}</span><b>{specs.find(s=>s.feature_spec_id===x.feature_spec_id)?.feature_name||x.feature_spec_id}</b><code>{x.dsl_expression}</code><small>{x.estimated_cost} cost · {x.operators?.join(', ')||'no operators'}</small>{x.capability_gap&&<div className="warning-box"><ShieldAlert size={14}/>Missing: {[...(x.capability_gap.missing_operator||[]),...(x.capability_gap.missing_data_source||[]),...(x.capability_gap.missing_fields||[])].join(', ')}</div>}{executable(x.compiler_status)&&<button disabled={!!busy} onClick={e=>{e.stopPropagation();if(window.confirm(`Generate feature from ${x.plan_id}?`))act(x.plan_id,()=>generateFeature(datasetId,x.plan_id))}}><Play size={13}/>{busy===x.plan_id?'Generating':'Generate Feature'}</button>}</article>)}</div>:<p className="muted">尚无编译计划。</p>}</section>}
  {tab==='generated'&&<section className="card"><h3>Generated Feature Registry</h3>{features.length?<div className="table-wrap"><table><thead><tr><th>Feature</th><th>Status</th><th>Version</th><th>Sources</th><th>Missing Policy</th><th>Action</th></tr></thead><tbody>{features.map(x=><tr key={x.feature_id} onClick={()=>setSelected(x)} className="clickable"><td><b>{x.feature_name}</b><small>{x.feature_id}</small></td><td><span className="tag tag-a">{x.status}</span></td><td>{x.version||x.feature_version}</td><td>{x.source_fields?.join(', ')}</td><td>{x.input_missing_policy} → {x.output_missing_policy}</td><td><button className="secondary" disabled={!!busy} onClick={e=>{e.stopPropagation();act(x.feature_id,()=>rebuildFeature(datasetId,x.feature_id))}}><CheckCircle2 size={13}/>Rebuild</button></td></tr>)}</tbody></table></div>:<p className="muted">尚无已生成人工特征。</p>}</section>}
  {capabilities&&<section className="card engine-capabilities"><h3>Capability Registry</h3><p><b>Operators</b> {capabilities.operators.join(', ')}</p><p><b>Windows</b> {capabilities.windows.join(', ')}</p><p><b>Unsupported examples</b> {capabilities.unsupported_examples.join(', ')}</p></section>}
  {selected&&<aside className="drawer"><button className="drawer-close" onClick={()=>setSelected(null)}>×</button><h2>Feature Detail</h2><div className="drawer-rule">{selected.feature_name||selected.plan_id||selected.execution_id}</div><div className="drawer-grid"><b>Compiler Status<small>{selected.compiler_status||'—'}</small></b><b>Execution Status<small>{selected.status||'—'}</small></b><b>Estimated Cost<small>{selected.estimated_cost||'—'}</small></b><b>Dataset Version<small>{selected.dataset_version?.slice(0,12)||'—'}</small></b></div><h3>DSL / Human Formula</h3><code>{selected.dsl_expression||selected.human_formula||'—'}</code><h3>AST / Lineage</h3><pre className="json-detail">{JSON.stringify(selected,null,2)}</pre></aside>}
 </div>
}
