import {useEffect,useState} from 'react';
import {AlertTriangle,BrainCircuit,CheckCircle2,FlaskConical,History,RotateCcw,Square,TestTube2} from 'lucide-react';
import {decideModelApproval,modelArtifacts,modelReportUrl,modelSummary,modelTimeline,rollbackModelAgent,runModelAgent,runModelExperiment,runModelRound,stopModelAgent} from '../api/client';
import {BusinessLabel,MetricHelp} from '../components/BusinessLabel';
import {actionLabels,diagnosisLabels,stopReasonLabels,validationLabels} from '../i18n/businessLabels';

type Props={datasetId:string;onError:(message:string)=>void};
const num=(v:any)=>v==null?'—':Number(v).toFixed(4);

export default function ModelAgentPage({datasetId,onError}:Props){
  const [data,setData]=useState<any>(null),[timeline,setTimeline]=useState<any[]>([]);
  const [artifacts,setArtifacts]=useState<any>({hypotheses:[],features:[],experiments:[],diagnoses:[],approvals:[]});
  const [busy,setBusy]=useState(false),[selected,setSelected]=useState<any>(null);
  const refresh=async()=>{if(!datasetId)return;try{const kinds=['hypotheses','features','experiments','diagnoses','approvals'] as const;const [s,t,...lists]=await Promise.all([modelSummary(datasetId),modelTimeline(datasetId),...kinds.map(x=>modelArtifacts(datasetId,x))]);setData(s.data);setTimeline(t.data);setArtifacts({hypotheses:lists[0].data,features:lists[1].data,experiments:lists[2].data,diagnoses:lists[3].data,approvals:lists[4].data})}catch(e:any){onError(e?.response?.data?.detail||e.message)}};
  useEffect(()=>{refresh()},[datasetId]);
  const act=async(fn:()=>Promise<any>)=>{setBusy(true);try{await fn();await refresh()}catch(e:any){onError(e?.response?.data?.detail||e.message)}finally{setBusy(false)}};
  if(!datasetId)return <div className="empty"><BrainCircuit size={34}/><b>请先导入数据</b><p>模型实验只处理 NEW 客群，并固定使用 target7。</p></div>;
  const state=data?.state||{},summary=data?.summary||{},rawLr=summary.lr_baseline||{},rawLgbm=summary.lgbm_baseline||{};
  const metricsStale=data?.metrics_status==='STALE_REINITIALIZATION_REQUIRED';
  const lr=metricsStale?{}:rawLr,lgbm=metricsStale?{}:rawLgbm;
  const proxyAudit=summary.target_proxy_audit||state.model_state?.target_proxy_audit||{};
  const quality=summary.data_quality||{};
  const suspiciousPerfect=[rawLr.oot_auc,rawLgbm.oot_auc].some(value=>Number(value)>=.995);
  const modelMetrics=(model:any)=><><div className="model-metrics"><span title="NEW 客群全部有标签样本，包含开发集；只用于总体描述，不用于选模">NEW 全量标注 <MetricHelp name="AUC"/><b>{num(model.overall_auc)}</b><small>{model.overall_rows?`${model.overall_rows} 行 · 描述性口径`:'旧结果无此口径'}</small></span><span>开发集 <MetricHelp name="AUC"/><b>{num(model.dev_auc)}</b><small>{model.dev_rows?`${model.dev_rows} 行`:'训练样本'}</small></span><span title="按申请时间留出的样本，是模型选择与验收的主指标"><MetricHelp name="OOT"/> <MetricHelp name="AUC"/><b>{num(model.oot_auc)}</b><small>{model.oot_rows?`${model.oot_rows} 行 · 选模口径`:'选模口径'}</small></span><span><MetricHelp name="OOT"/> <MetricHelp name="KS"/><b>{num(model.oot_ks)}</b></span><span>训练与验证差距<b>{num(model.train_oot_auc_gap)}</b></span><span><MetricHelp name="Lift"/>@10<b>{num(model.lift_at_10)}</b></span></div><p className="muted">“NEW 全量标注 AUC”用于看当前建模样本整体区分度；它包含开发集，不能替代 OOT AUC。模型选择仍严格使用 OOT。</p></>;
  return <div className="model-agent-page">
    <div className="page-title"><div><h2>模型实验</h2><p>NEW 客群 · target7 · 最多 3 轮 · 可诊断、可回退、需人工审批</p></div><div className="agent-actions"><button disabled={busy} onClick={()=>act(()=>runModelAgent(datasetId))}><BrainCircuit size={15}/>初始化</button><button disabled={busy||!state.current_state_id} onClick={()=>act(()=>runModelExperiment(datasetId))}><TestTube2 size={15}/>下一实验</button><button disabled={busy||!state.current_state_id} onClick={()=>act(()=>runModelRound(datasetId))}><FlaskConical size={15}/>运行一轮</button><button className="secondary" disabled={busy||!state.current_state_id} onClick={()=>act(()=>rollbackModelAgent(datasetId))}><RotateCcw size={15}/>回退版本</button><button className="danger-button" disabled={busy||!state.current_state_id} onClick={()=>act(()=>stopModelAgent(datasetId))}><Square size={14}/>停止</button><button className="secondary" onClick={()=>window.open(modelReportUrl(datasetId),'_blank')}>导出报告</button></div></div>
    {busy&&<div className="progress-banner">模型实验运行中<i/><i/><i/></div>}
    <div className="metrics compact"><div className="metric-card tone-a"><span>实验助手状态</span><b><BusinessLabel value={state.stop_reason?'STOPPED':state.current_state_id?'ACTIVE':'READY'}/></b><small>{state.stop_reason?<BusinessLabel value={state.stop_reason} map={stopReasonLabels} className="status-dot"/>:'可继续实验'}</small></div><div className="metric-card"><span>轮次</span><b>{state.round_index||0}/{state.max_rounds||3}</b><small>硬上限 3 轮</small></div><div className="metric-card"><span>当前最佳模型</span><b>{summary.champion||'—'}</b><small>NEW 客群基线</small></div><div className="metric-card"><span>实验预算</span><b>{state.budget?.experiments??'—'}</b><small>剩余次数</small></div><div className="metric-card tone-review"><span>待人工审批</span><b>{state.pending_human_approval?.length||0}</b><small>不会自动上线</small></div></div>
    <div className="state-pointer"><span><small>当前版本</small>{state.current_state_id||'—'}</span><span><small>当前最佳版本</small>{state.best_state_id||'—'}</span><span><small>最近稳定版本</small>{state.last_stable_state_id||'—'}</span></div>
    {(metricsStale||suspiciousPerfect||proxyAudit.excluded_fields?.length>0)&&<div className="warning-box"><AlertTriangle size={16}/><div><b>{metricsStale?'旧版 AUC 已失效，不再展示':proxyAudit.excluded_fields?.length?'已拦截疑似目标代理字段':'AUC 接近 1，结果需要重新初始化核查'}</b><p>{metricsStale?'当前持久化结果没有 Metric V2 和目标代理审计，不能用于选模或反事实。请点击“初始化”，从治理后的原始字段重新挖掘。':proxyAudit.excluded_fields?.length?`跨 DEV/OOT 近乎完美复现 target7，已从基线剔除：${proxyAudit.excluded_fields.join(', ')}`:'历史结果可能包含强目标代理或结果泄漏字段。请点击“初始化”重新运行，新版本会自动执行跨时间目标代理检查。'}</p></div></div>}
    <div className="warning-box"><BrainCircuit size={16}/><div><b>模型挖掘来源：治理后的原始数据字段</b><p>模型基线、候选特征和反事实均不依赖规则挖掘结果；规则页只保留为独立的策略分析工具。</p></div></div>
    {quality.source_rows&&<div className="warning-box"><AlertTriangle size={16}/><div><b>数据口径：模型不是全表直接训练</b><p>源数据 {quality.source_rows} 行；有效标签 {quality.labelled_rows} 行（{(quality.label_coverage*100).toFixed(1)}%）；NEW 有效标签 {quality.new_labelled_rows} 行，其中 DEV {quality.dev_rows}、OOT {quality.oot_rows}。当前模型指标仅代表 NEW 有标签客群。</p></div></div>}
    <div className="grid-2"><section className="card"><h3>LR 基线</h3>{modelMetrics(lr)}</section><section className="card"><h3>LightGBM 基线</h3>{modelMetrics(lgbm)}</section></div>
    <div className="grid-2"><section className="card"><h3>风险假设看板</h3><div className="agent-list">{artifacts.hypotheses.length?artifacts.hypotheses.map((x:any)=><button className="agent-row" key={x.hypothesis_id} onClick={()=>setSelected(x)}><BusinessLabel value={x.status} className={`tag tag-${String(x.status||'review').toLowerCase()}`}/><b>{x.title||x.hypothesis_id}</b><small>置信度 {x.confidence} · {x.hypothesis_type}</small></button>):<p className="muted">暂无风险假设</p>}</div></section><section className="card"><h3>候选特征清单</h3><div className="agent-list">{artifacts.features.length?artifacts.features.map((x:any)=><button className="agent-row" key={x.feature_id} onClick={()=>setSelected(x)}><BusinessLabel value={x.status} map={validationLabels} className={`tag tag-${String(x.status||'review').toLowerCase()}`}/><b>{x.feature_name}</b><small><MetricHelp name="IV"/> {num(x.validation_result?.iv)} · <MetricHelp name="PSI"/> {num(x.validation_result?.psi)}</small></button>):<p className="muted">暂无候选特征</p>}</div></section></div>
    <section className="card agent-section"><h3>实验记录</h3><div className="table-wrap"><table><thead><tr><th>实验</th><th>类型</th><th>模型</th><th>决策</th><th>OOT AUC 前 / 后</th><th>回退状态</th></tr></thead><tbody>{artifacts.experiments.map((x:any)=><tr className="clickable" key={x.experiment_id} onClick={()=>setSelected(x)}><td>{x.experiment_id}</td><td>{x.experiment_type}</td><td>{x.model_type}</td><td><BusinessLabel value={x.decision} className={`tag ${String(x.decision).startsWith('ACCEPT')?'tag-a':x.decision==='RUNNING'?'tag-b':'tag-review'}`}/></td><td>{num(x.metrics_before?.oot_auc)} → {num(x.metrics_after?.oot_auc)}</td><td>{x.rollback_state_id||'—'}</td></tr>)}</tbody></table></div></section>
    <div className="grid-2 agent-section"><section className="card"><h3><AlertTriangle size={15}/> 问题诊断</h3>{artifacts.diagnoses.length?artifacts.diagnoses.map((x:any)=><div className="diagnosis" key={x.diagnosis_id}><b><BusinessLabel value={x.diagnosis_type} map={diagnosisLabels}/></b><p>{String(x.evidence||'')}</p><small>{x.recommended_action}</small></div>):<p className="muted">暂无诊断</p>}</section><section className="card"><h3><CheckCircle2 size={15}/> 人工审批</h3>{artifacts.approvals.length?artifacts.approvals.map((x:any)=><div className="approval" key={x.approval_id}><div><b><BusinessLabel value={x.action_type} map={actionLabels}/></b><p>{x.reason}</p><BusinessLabel value={x.status}/></div>{x.status==='PENDING'&&<span><button onClick={()=>act(()=>decideModelApproval(datasetId,x.approval_id,'APPROVE'))}>同意并继续</button><button className="danger-button" onClick={()=>act(()=>decideModelApproval(datasetId,x.approval_id,'REJECT'))}>拒绝</button></span>}</div>):<p className="muted">暂无待审批事项</p>}</section></div>
    <section className="card agent-section"><h3><History size={15}/> 实验时间线</h3><div className="timeline">{timeline.length?timeline.map((x:any)=><div key={`${x.type}-${x.id}`}><i/><span><small>{x.time?.replace('T',' ').slice(0,19)} · {x.type}</small><b>{x.title}</b><em><BusinessLabel value={x.status}/></em></span></div>):<p className="muted">暂无模型实验记录。</p>}</div></section>
    {selected&&<aside className="drawer"><button className="drawer-close" onClick={()=>setSelected(null)}>×</button><h2>对象详情</h2><div className="drawer-rule">{selected.feature_name||selected.title||selected.experiment_id}</div>{selected.formula&&<><h3>公式</h3><code>{selected.formula}</code></>}{selected.human_description&&<p>{selected.human_description}</p>}<div className="drawer-grid"><b>状态<small><BusinessLabel value={selected.status||selected.decision}/></small></b><b>类型<small>{selected.feature_type||selected.hypothesis_type||selected.experiment_type}</small></b><b>OOT AUC<small>{num(selected.metrics_after?.oot_auc)}</small></b><b>PSI<small>{num(selected.validation_result?.psi)}</small></b></div><h3>高级详情 / 完整审计数据</h3><pre className="json-detail">{JSON.stringify(selected,null,2)}</pre></aside>}
  </div>;
}
