import {useEffect,useState} from 'react';
import {AlertTriangle,BrainCircuit,CheckCircle2,FlaskConical,History,RotateCcw,Square,TestTube2} from 'lucide-react';
import {decideModelApproval,modelArtifacts,modelReportUrl,modelSummary,modelTimeline,rollbackModelAgent,runModelAgent,runModelExperiment,runModelRound,stopModelAgent} from '../api/client';

type Props={datasetId:string; onError:(message:string)=>void};
const num=(v:any)=>v==null?'—':Number(v).toFixed(4);

export default function ModelAgentPage({datasetId,onError}:Props){
  const [data,setData]=useState<any>(null),[timeline,setTimeline]=useState<any[]>([]),[artifacts,setArtifacts]=useState<any>({hypotheses:[],features:[],experiments:[],diagnoses:[],approvals:[]}),[busy,setBusy]=useState(false),[selected,setSelected]=useState<any>(null);
  const refresh=async()=>{if(!datasetId)return;try{const kinds=['hypotheses','features','experiments','diagnoses','approvals'] as const;const [s,t,...lists]=await Promise.all([modelSummary(datasetId),modelTimeline(datasetId),...kinds.map(x=>modelArtifacts(datasetId,x))]);setData(s.data);setTimeline(t.data);setArtifacts({hypotheses:lists[0].data,features:lists[1].data,experiments:lists[2].data,diagnoses:lists[3].data,approvals:lists[4].data})}catch(e:any){onError(e?.response?.data?.detail||e.message)}};
  useEffect(()=>{refresh()},[datasetId]);
  const act=async(fn:()=>Promise<any>)=>{setBusy(true);try{await fn();await refresh()}catch(e:any){onError(e?.response?.data?.detail||e.message)}finally{setBusy(false)}};
  if(!datasetId)return <div className="empty"><BrainCircuit size={34}/><b>请先导入数据</b><p>模型实验 Agent 只处理 NEW 客群，并固定使用 target7。</p></div>;
  const state=data?.state||{},summary=data?.summary||{},lr=summary.lr_baseline||{},lgbm=summary.lgbm_baseline||{};
  return <div className="model-agent-page">
    <div className="page-title"><div><h2>模型实验 Agent</h2><p>NEW 客群 · target7 · 最多 3 轮 · 可诊断、可回滚、需人工审批</p></div><div className="agent-actions"><button disabled={busy} onClick={()=>act(()=>runModelAgent(datasetId))}><BrainCircuit size={15}/>初始化</button><button disabled={busy||!state.current_state_id} onClick={()=>act(()=>runModelExperiment(datasetId))}><TestTube2 size={15}/>下一实验</button><button disabled={busy||!state.current_state_id} onClick={()=>act(()=>runModelRound(datasetId))}><FlaskConical size={15}/>运行一轮</button><button className="secondary" disabled={busy||!state.current_state_id} onClick={()=>act(()=>rollbackModelAgent(datasetId))}><RotateCcw size={15}/>回滚</button><button className="danger-button" disabled={busy||!state.current_state_id} onClick={()=>act(()=>stopModelAgent(datasetId))}><Square size={14}/>停止</button><button className="secondary" onClick={()=>window.open(modelReportUrl(datasetId),'_blank')}>导出报告</button></div></div>
    {busy&&<div className="progress-banner">模型实验运行中<i/><i/><i/></div>}
    <div className="metrics compact"><div className="metric-card tone-a"><span>Agent 状态</span><b>{state.stop_reason?'STOPPED':state.current_state_id?'ACTIVE':'READY'}</b><small>{state.stop_reason||'可继续实验'}</small></div><div className="metric-card"><span>轮次</span><b>{state.round_index||0}/{state.max_rounds||3}</b><small>硬上限 3 轮</small></div><div className="metric-card"><span>Champion</span><b>{summary.champion||'—'}</b><small>NEW baseline</small></div><div className="metric-card"><span>实验预算</span><b>{state.budget?.experiments??'—'}</b><small>剩余次数</small></div><div className="metric-card tone-review"><span>待人工审批</span><b>{state.pending_human_approval?.length||0}</b><small>不会自动上线</small></div></div>
    <div className="state-pointer"><span><small>CURRENT</small>{state.current_state_id||'—'}</span><span><small>BEST</small>{state.best_state_id||'—'}</span><span><small>LAST_STABLE</small>{state.last_stable_state_id||'—'}</span></div>
    <div className="grid-2"><section className="card"><h3>LR 基线</h3><div className="model-metrics"><span>DEV AUC<b>{num(lr.dev_auc)}</b></span><span>OOT AUC<b>{num(lr.oot_auc)}</b></span><span>OOT KS<b>{num(lr.oot_ks)}</b></span><span>Gap<b>{num(lr.train_oot_auc_gap)}</b></span><span>Lift@10<b>{num(lr.lift_at_10)}</b></span></div></section><section className="card"><h3>LightGBM 基线</h3><div className="model-metrics"><span>DEV AUC<b>{num(lgbm.dev_auc)}</b></span><span>OOT AUC<b>{num(lgbm.oot_auc)}</b></span><span>OOT KS<b>{num(lgbm.oot_ks)}</b></span><span>Gap<b>{num(lgbm.train_oot_auc_gap)}</b></span><span>Lift@10<b>{num(lgbm.lift_at_10)}</b></span></div></section></div>
    <div className="grid-2"><section className="card"><h3>假设看板</h3><div className="agent-list">{artifacts.hypotheses.length?artifacts.hypotheses.map((x:any)=><button className="agent-row" key={x.hypothesis_id} onClick={()=>setSelected(x)}><span className={`tag tag-${String(x.status||'review').toLowerCase()}`}>{x.status}</span><b>{x.title||x.hypothesis_id}</b><small>{x.confidence} · {x.hypothesis_type}</small></button>):<p className="muted">尚无假设</p>}</div></section><section className="card"><h3>特征注册表</h3><div className="agent-list">{artifacts.features.length?artifacts.features.map((x:any)=><button className="agent-row" key={x.feature_id} onClick={()=>setSelected(x)}><span className={`tag tag-${String(x.status||'review').toLowerCase()}`}>{x.status}</span><b>{x.feature_name}</b><small>IV {num(x.validation_result?.iv)} · PSI {num(x.validation_result?.psi)}</small></button>):<p className="muted">尚无候选特征</p>}</div></section></div>
    <section className="card agent-section"><h3>实验记录</h3><div className="table-wrap"><table><thead><tr><th>实验</th><th>类型</th><th>模型</th><th>决策</th><th>OOT AUC 前/后</th><th>回滚状态</th></tr></thead><tbody>{artifacts.experiments.map((x:any)=><tr className="clickable" key={x.experiment_id} onClick={()=>setSelected(x)}><td>{x.experiment_id}</td><td>{x.experiment_type}</td><td>{x.model_type}</td><td><span className={`tag ${String(x.decision).startsWith('ACCEPT')?'tag-a':x.decision==='RUNNING'?'tag-b':'tag-review'}`}>{x.decision}</span></td><td>{num(x.metrics_before?.oot_auc)} → {num(x.metrics_after?.oot_auc)}</td><td>{x.rollback_state_id||'—'}</td></tr>)}</tbody></table></div></section>
    <div className="grid-2 agent-section"><section className="card"><h3><AlertTriangle size={15}/> 诊断</h3>{artifacts.diagnoses.length?artifacts.diagnoses.map((x:any)=><div className="diagnosis" key={x.diagnosis_id}><b>{x.diagnosis_type}</b><p>{String(x.evidence||'')}</p><small>{x.recommended_action}</small></div>):<p className="muted">暂无诊断</p>}</section><section className="card"><h3><CheckCircle2 size={15}/> 人工审批</h3>{artifacts.approvals.length?artifacts.approvals.map((x:any)=><div className="approval" key={x.approval_id}><div><b>{x.action_type}</b><p>{x.reason}</p><small>{x.status}</small></div>{x.status==='PENDING'&&<span><button onClick={()=>act(()=>decideModelApproval(datasetId,x.approval_id,'APPROVE'))}>批准</button><button className="danger-button" onClick={()=>act(()=>decideModelApproval(datasetId,x.approval_id,'REJECT'))}>拒绝</button></span>}</div>):<p className="muted">暂无待审批事项</p>}</section></div>
    <section className="card agent-section"><h3><History size={15}/> Agent 时间线</h3><div className="timeline">{timeline.map((x:any)=><div key={`${x.type}-${x.id}`}><i/><span><small>{x.time?.replace('T',' ').slice(0,19)} · {x.type}</small><b>{x.title}</b><em>{x.status||'—'}</em></span></div>)}</div></section>
    {selected&&<aside className="drawer"><button className="drawer-close" onClick={()=>setSelected(null)}>×</button><h2>对象详情</h2><div className="drawer-rule">{selected.feature_name||selected.title||selected.experiment_id}</div>{selected.formula&&<><h3>公式</h3><code>{selected.formula}</code></>}{selected.human_description&&<p>{selected.human_description}</p>}<div className="drawer-grid"><b>状态<small>{selected.status||selected.decision}</small></b><b>类型<small>{selected.feature_type||selected.hypothesis_type||selected.experiment_type}</small></b><b>OOT AUC<small>{num(selected.metrics_after?.oot_auc)}</small></b><b>PSI<small>{num(selected.validation_result?.psi)}</small></b></div><h3>完整审计数据</h3><pre className="json-detail">{JSON.stringify(selected,null,2)}</pre></aside>}
  </div>
}
