import {useEffect,useMemo,useState} from 'react';
import {Metric,Tag,Empty} from '../components/Common';
import {BusinessLabel,MetricHelp} from '../components/BusinessLabel';
import Chart from '../components/Chart';
import {groups,groupMatrix} from '../api/client';
import type {Rule} from '../types';

export default function RulesPage({rows,onSelect,datasetId}:{rows:Rule[];onSelect:(r:Rule)=>void;datasetId?:string}){
  const [seg,setSeg]=useState('ALL'),[activeSeg,setActiveSeg]=useState('NEW'),[grade,setGrade]=useState('ALL'),[q,setQ]=useState(''),[rep,setRep]=useState(true),[low,setLow]=useState(false),[ootFailed,setOotFailed]=useState(false),[view,setView]=useState('table'),[groupsData,setGroupsData]=useState<any[]>([]),[matrix,setMatrix]=useState<any>(null),[threshold,setThreshold]=useState(.9);
  const filtered=useMemo(()=>rows.filter(r=>(seg==='ALL'||r.segment===seg)&&(grade==='ALL'||r.grade===grade)&&(!ootFailed||r.oot_status==='FAILED')&&(r.field+r.rule).toLowerCase().includes(q.toLowerCase())&&(rep?r.is_representative!==false:true)&&(low||!r.small_segment)),[rows,seg,grade,ootFailed,q,rep,low]);
  useEffect(()=>{if(datasetId)groups(datasetId).then(r=>setGroupsData(r.data.groups||r.data)).catch(()=>{});},[datasetId,rows]);
  const clusterSeg=seg==='ALL'?activeSeg:seg;
  useEffect(()=>{if(datasetId&&view!=='table')groupMatrix(datasetId,clusterSeg,threshold).then(r=>setMatrix(r.data)).catch(()=>setMatrix(null));},[datasetId,view,clusterSeg,threshold,rows]);
  const heat=matrix?{tooltip:{},visualMap:{min:0,max:1,calculable:true,orient:'horizontal',left:'center',bottom:0},xAxis:{type:'category',data:matrix.rule_ids},yAxis:{type:'category',data:matrix.rule_ids},series:[{type:'heatmap',data:matrix.matrix.flatMap((line:number[],i:number)=>line.map((v:number,j:number)=>[j,i,v]))}]}:null;
  const network=matrix?{tooltip:{},series:[{type:'graph',layout:'force',roam:true,force:{repulsion:120},data:matrix.nodes.map((n:any)=>({...n,symbolSize:10+Math.round((n.coverage||0)*18)+(n.is_representative?6:0),itemStyle:{color:n.is_representative?'#315efb':'#94a3b8'}})),links:matrix.edges,label:{show:true,position:'right'},lineStyle:{opacity:.65}}]}:null;
  return <div className="page"><div className="page-title"><div><h2>规则中心</h2><p>统一查看代表规则、<MetricHelp name="OOT"/> 稳定性和规则组聚类。</p></div></div>
    <div className="metrics compact"><Metric label="代表规则" value={rows.filter(r=>r.is_representative!==false).length}/><Metric label="A级规则" value={rows.filter(r=>r.grade==='A').length}/><Metric label="B级规则" value={rows.filter(r=>r.grade==='B').length}/><Metric label="OOT 验证失败" value={rows.filter(r=>r.oot_status==='FAILED').length}/></div>
    <div className="toolbar"><select aria-label="客群筛选" value={seg} onChange={e=>{setSeg(e.target.value);setMatrix(null)}}><option value="ALL">全部客群</option><option value="NEW">新客</option><option value="OLD">老客</option></select><select aria-label="规则等级筛选" value={grade} onChange={e=>setGrade(e.target.value)}><option value="ALL">全部等级</option><option value="A">A级</option><option value="B">B级</option><option value="REVIEW">需人工复核</option><option value="C">C级</option></select><input placeholder="字段 / 规则搜索" value={q} onChange={e=>setQ(e.target.value)}/><label className="switch"><input type="checkbox" checked={ootFailed} onChange={e=>setOotFailed(e.target.checked)}/>只看 OOT 验证失败</label><label className="switch"><input type="checkbox" checked={rep} onChange={e=>setRep(e.target.checked)}/>仅代表规则</label><label className="switch"><input type="checkbox" checked={low} onChange={e=>setLow(e.target.checked)}/>显示低样本</label><button onClick={()=>setView('table')}>规则表</button><button onClick={()=>setView('cluster')}>聚类网络</button><button onClick={()=>setView('matrix')}>相似度矩阵</button></div>
    {view!=='table'&&<div className="toolbar"><b>聚类客群：</b><button className={clusterSeg==='NEW'?'active':''} onClick={()=>{setActiveSeg('NEW');setMatrix(null)}}>新客</button><button className={clusterSeg==='OLD'?'active':''} onClick={()=>{setActiveSeg('OLD');setMatrix(null)}}>老客</button><span>同组阈值：0.90</span><span>显示阈值：{threshold.toFixed(2)}</span><input aria-label="相似度显示阈值" type="range" min=".8" max="1" step=".01" value={threshold} onChange={e=>setThreshold(Number(e.target.value))}/></div>}
    {view==='table'?<div className="table-wrap">{filtered.length?<table><thead><tr><th>等级</th><th>客群</th><th>字段</th><th>规则</th><th>命中 / 坏样本</th><th><MetricHelp name="Coverage"/></th><th><MetricHelp name="Lift"/></th><th>采样稳定性</th><th><MetricHelp name="OOT"/></th><th>OOT Lift</th><th>规则组</th></tr></thead><tbody>{filtered.map((r,i)=><tr key={i} onClick={()=>onSelect(r)} className="clickable"><td><Tag>{r.grade}</Tag></td><td>{r.segment==='NEW'?'新客':'老客'}</td><td>{r.field}</td><td>{r.rule}</td><td>{r.hit_count} / {r.bad_count}</td><td>{(r.coverage*100).toFixed(2)}%</td><td>{r.lift?.toFixed(2)}</td><td>{(r.bootstrap_positive_ratio*100).toFixed(1)}%</td><td><BusinessLabel value={r.oot_status||'NOT_AVAILABLE'} className="tag"/></td><td>{r.oot_lift?.toFixed(2)||'—'}</td><td>{r.rule_group_id}</td></tr>)}</tbody></table>:<Empty title="当前筛选条件下暂无候选规则" text="可以关闭“仅代表规则”或选择“显示低样本”。"/>}</div>:<div className="card chart-card"><div className="section-header"><h3>{view==='cluster'?'规则组网络':'规则相似度矩阵'}</h3></div>{matrix?(view==='cluster'?<Chart option={network}/>:<Chart option={heat}/>):<Empty title="暂无相似度矩阵" text="请先完成候选规则、稳定性和规则组阶段。"/>}</div>}
    {view==='cluster'&&groupsData.length>0&&<div className="table-wrap"><table><thead><tr><th>规则组</th><th>客群</th><th>规则数</th><th>代表规则</th><th>OOT 状态</th></tr></thead><tbody>{groupsData.filter(g=>g.representative?.segment===clusterSeg).map(g=><tr key={g.rule_group_id}><td>{g.rule_group_id}</td><td>{g.representative?.segment==='NEW'?'新客':'老客'}</td><td>{g.count}</td><td>{g.representative?.rule}</td><td><BusinessLabel value={g.representative?.oot_status||'NOT_AVAILABLE'}/></td></tr>)}</tbody></table></div>}
  </div>;
}
