import {useState} from 'react';
import {upload,governance,patchGovernance,runAnalysis,rules,overview,variable,exportUrl,state,runStage,runAll} from './api/client';
import {Sidebar,Header} from './components/Layout';
import ImportPage from './pages/ImportPage'; import OverviewPage from './pages/OverviewPage'; import GovernancePage from './pages/GovernancePage'; import MiningPage from './pages/MiningPage'; import RulesPage from './pages/RulesPage'; import VariablePage from './pages/VariablePage'; import ReportPage from './pages/ReportPage';
import type {Governance,Rule} from './types';
import WorkflowStepper from './components/WorkflowStepper';

const titles:any={import:'数据导入',overview:'数据概览',governance:'字段治理',mining:'策略挖掘',rules:'规则中心',variables:'变量分析',report:'分析报告'};
export default function App(){
  const [page,setPage]=useState('import'),[collapsed,setCollapsed]=useState(false),[id,setId]=useState(''),[filename,setFilename]=useState(''),[info,setInfo]=useState<any>(null),[gov,setGov]=useState<Governance[]>([]),[rows,setRows]=useState<Rule[]>([]),[dash,setDash]=useState<any>(null),[workflow,setWorkflow]=useState<any>({}),[selected,setSelected]=useState<Rule|null>(null),[variableField,setVariableField]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const safe=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn()}catch(e:any){setError(e?.response?.data?.detail||e?.message||'操作失败')}finally{setBusy(false)}};
  const refreshState=async(datasetId:string)=>{const s=await state(datasetId);setWorkflow(s.data.stage_status)};
  const onUpload=(file:File)=>safe(async()=>{const r=await upload(file);setId(r.data.dataset_id);setFilename(file.name);setInfo(r.data);await refreshState(r.data.dataset_id);setPage('import')});
  const loadGov=()=>safe(async()=>{const r=await governance(id);setGov(r.data.items);setPage('governance')});
  const run=()=>safe(async()=>{const r=await runAll(id,{});setWorkflow(r.data.state.stage_status);const [o,rr]=await Promise.all([overview(id),rules(id)]);setDash(o.data);setRows(rr.data);setPage('overview')});
  const runOne=(stage:string,mode:'CURRENT'|'FROM_HERE'='CURRENT')=>safe(async()=>{await runStage(id,stage.replace('_','-'),{mode});await refreshState(id);if(['grading','report','rule_groups','candidate_rules','stability'].includes(stage)){const [o,rr]=await Promise.all([overview(id),rules(id)]);setDash(o.data);setRows(rr.data)}if(stage==='governance'){const g=await governance(id);setGov(g.data.items)} });
  const openRule=async(r:Rule)=>{setSelected(r);setVariableField(r.field);try{const detail=await variable(id,r.field);setSelected({...r,...detail.data})}catch{}}
  const pageBody=page==='import'?<ImportPage info={info} onUpload={onUpload} busy={busy}/>:page==='overview'?<OverviewPage data={dash}/>:page==='governance'?<GovernancePage rows={gov} onChange={(field,d)=>safe(async()=>{await patchGovernance(id,field,d);setGov(gov.map(x=>x.field===field?{...x,decision:d}:x))})}/>:page==='mining'?<MiningPage data={dash} rules={rows} onRun={run}/>:page==='rules'?<RulesPage rows={rows} datasetId={id} onSelect={openRule}/>:page==='variables'?<VariablePage datasetId={id} field={variableField} onField={setVariableField}/>:<ReportPage datasetId={id}/>;
  return <div className="app-shell"><Sidebar page={page} setPage={setPage} collapsed={collapsed} setCollapsed={setCollapsed} filename={filename}/><div className="main-shell"><Header title={titles[page]} datasetId={id} status={busy?'RUNNING':workflow.report==='SUCCESS'?'SUCCESS':workflow.report==='STALE'?'STALE':'未开始'} onImport={()=>setPage('import')} onExport={()=>id&&window.open(exportUrl(id,'all'),'_blank')} onReanalyze={run}/><main className="workspace">{error&&<div className="error-banner">{error}</div>}{busy&&<div className="progress-banner"><span>分析处理中</span><i/><i/><i/></div>}{id&&<WorkflowStepper statuses={workflow} onRun={runOne}/>} {pageBody}</main></div>{selected&&<aside className="drawer"><button className="drawer-close" onClick={()=>setSelected(null)}>×</button><h2>Rule Detail</h2><span className="drawer-rule">{selected.rule}</span><div className="drawer-grid"><b>Field<small>{selected.field}</small></b><b>Segment<small>{selected.segment}</small></b><b>Hit<small>{selected.hit_count}</small></b><b>Coverage<small>{selected.coverage!=null?(selected.coverage*100).toFixed(2)+'%':'—'}</small></b><b>Bad Rate<small>{selected.bad_rate!=null?(selected.bad_rate*100).toFixed(2)+'%':'—'}</small></b><b>Lift<small>{selected.lift?.toFixed(2)}</small></b><b>Sampling Stability<small>{selected.bootstrap_positive_ratio!=null?(selected.bootstrap_positive_ratio*100).toFixed(1)+'%':'—'}</small></b><b>Rule Group<small>{selected.rule_group_id||'—'}</small></b></div><h3>为什么产生该规则</h3><p>{selected.reason||'代码识别到连续高风险尾部或类别高风险组。'}</p>{(selected.warning||selected.review_reason)&&<div className="warning-box">{selected.warning||selected.review_reason}</div>}<button onClick={()=>{setVariableField(selected.field);setSelected(null);setPage('variables')}}>查看变量证据</button></aside>}</div>
}
