import {useState} from 'react';
import {upload,governance,patchGovernance,rules,overview,variable,exportUrl,state,runStage,runAll} from './api/client';
import {Sidebar,Header} from './components/Layout';
import ImportPage from './pages/ImportPage'; import OverviewPage from './pages/OverviewPage'; import GovernancePage from './pages/GovernancePage'; import MiningPage from './pages/MiningPage'; import RulesPage from './pages/RulesPage'; import VariablePage from './pages/VariablePage'; import ReportPage from './pages/ReportPage'; import ModelAgentPage from './pages/ModelAgentPage'; import AgentChatPage from './pages/AgentChatPage'; import FeatureEnginePage from './pages/FeatureEnginePage'; import DecisionLoopPage from './pages/DecisionLoopPage'; import ExperimentMemoryPage from './pages/ExperimentMemoryPage'; import ShadowDashboardPage from './pages/ShadowDashboardPage'; import WorkflowRunPage from './pages/WorkflowRunPage'; import GuidePage from './pages/GuidePage';
import type {Governance,Rule} from './types';
import WorkflowStepper from './components/WorkflowStepper';
import './guide.css';

const titles:any={guide:'使用指南',import:'数据导入',overview:'数据概览',governance:'字段治理',mining:'策略挖掘',rules:'规则中心',variables:'变量分析',report:'分析报告','model-agent':'模型实验','agent-chat':'风险分析助手','feature-engine':'候选特征','decision-loop':'实验决策助手','experiment-memory':'实验记忆','surrogate-shadow':'历史实验预测','workflow-run':'风险研究工作流'};
export default function App(){
  const [page,setPage]=useState('import'),[collapsed,setCollapsed]=useState(false),[id,setId]=useState(''),[filename,setFilename]=useState(''),[info,setInfo]=useState<any>(null),[gov,setGov]=useState<Governance[]>([]),[rows,setRows]=useState<Rule[]>([]),[dash,setDash]=useState<any>(null),[workflow,setWorkflow]=useState<any>({}),[selected,setSelected]=useState<Rule|null>(null),[variableField,setVariableField]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const safe=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn()}catch(e:any){setError(e?.response?.data?.detail||e?.message||'操作失败')}finally{setBusy(false)}};
  const refreshState=async(datasetId:string)=>{const s=await state(datasetId);setWorkflow(s.data.stage_status)};
  const onUpload=(file:File)=>safe(async()=>{const r=await upload(file);setId(r.data.dataset_id);setFilename(file.name);setInfo(r.data);await refreshState(r.data.dataset_id);setPage('import')});
  const run=()=>safe(async()=>{const r=await runAll(id,{});setWorkflow(r.data.state.stage_status);const [o,rr]=await Promise.all([overview(id),rules(id)]);setDash(o.data);setRows(rr.data);setPage('overview')});
  const runOne=(stage:string,mode:'CURRENT'|'FROM_HERE'='CURRENT')=>safe(async()=>{await runStage(id,stage.replace('_','-'),{mode});await refreshState(id);if(['grading','report','rule_groups','candidate_rules','stability'].includes(stage)){const [o,rr]=await Promise.all([overview(id),rules(id)]);setDash(o.data);setRows(rr.data)}if(stage==='governance'){const g=await governance(id);setGov(g.data.items)}});
  const openRule=async(r:Rule)=>{setSelected(r);setVariableField(r.field);try{const detail=await variable(id,r.field);setSelected({...r,...detail.data})}catch{}}
  const pageBody=page==='guide'?<GuidePage onNavigate={setPage}/>:page==='agent-chat'?<AgentChatPage datasetId={id} onError={setError}/>:page==='feature-engine'?<FeatureEnginePage datasetId={id} onError={setError}/>:page==='decision-loop'?<DecisionLoopPage datasetId={id} onError={setError}/>:page==='experiment-memory'?<ExperimentMemoryPage datasetId={id} onError={setError}/>:page==='surrogate-shadow'?<ShadowDashboardPage datasetId={id} onError={setError}/>:page==='workflow-run'?<WorkflowRunPage datasetId={id} onError={setError}/>:page==='import'?<ImportPage info={info} onUpload={onUpload} busy={busy}/>:page==='overview'?<OverviewPage data={dash}/>:page==='governance'?<GovernancePage rows={gov} onChange={(field,d)=>safe(async()=>{await patchGovernance(id,field,d);setGov(gov.map(x=>x.field===field?{...x,decision:d}:x))})}/>:page==='mining'?<MiningPage data={dash} rules={rows} onRun={run}/>:page==='rules'?<RulesPage rows={rows} datasetId={id} onSelect={openRule}/>:page==='variables'?<VariablePage datasetId={id} field={variableField} onField={setVariableField}/>:page==='model-agent'?<ModelAgentPage datasetId={id} onError={setError}/>:<ReportPage datasetId={id}/>;
  return <div className="app-shell"><Sidebar page={page} setPage={setPage} collapsed={collapsed} setCollapsed={setCollapsed} filename={filename}/><div className="main-shell"><Header title={titles[page]} datasetId={id} status={busy?'RUNNING':workflow.report==='SUCCESS'?'SUCCESS':workflow.report==='STALE'?'STALE':'NOT_STARTED'} onGuide={()=>setPage('guide')} onImport={()=>setPage('import')} onExport={()=>id&&window.open(exportUrl(id,'all'),'_blank')} onReanalyze={run}/><main className="workspace">{error&&<div className="error-banner">{error}</div>}{busy&&<div className="progress-banner">分析处理中<i/><i/><i/></div>}{id&&!['guide','model-agent','feature-engine','agent-chat','decision-loop'].includes(page)&&<WorkflowStepper statuses={workflow} onRun={runOne}/>} {pageBody}</main></div>{selected&&<aside className="drawer"><button className="drawer-close" onClick={()=>setSelected(null)}>×</button><h2>规则详情</h2><span className="drawer-rule">{selected.rule}</span><div className="drawer-grid"><b>字段<small>{selected.field}</small></b><b>客群<small>{selected.segment}</small></b><b>命中<small>{selected.hit_count}</small></b><b>覆盖率<small>{selected.coverage!=null?(selected.coverage*100).toFixed(2)+'%':'—'}</small></b><b>坏账率<small>{selected.bad_rate!=null?(selected.bad_rate*100).toFixed(2)+'%':'—'}</small></b><b>Lift<small>{selected.lift?.toFixed(2)}</small></b><b>采样稳定性<small>{selected.bootstrap_positive_ratio!=null?(selected.bootstrap_positive_ratio*100).toFixed(1)+'%':'—'}</small></b><b>规则组<small>{selected.rule_group_id||'—'}</small></b></div><h3>为什么产生该规则</h3><p>{selected.reason||'代码识别到连续高风险尾部或类别高风险组。'}</p>{(selected.warning||selected.review_reason)&&<div className="warning-box">{selected.warning||selected.review_reason}</div>}<button onClick={()=>{setVariableField(selected.field);setSelected(null);setPage('variables')}}>查看变量证据</button></aside>}</div>
}
